### PR TITLE
Route badly interpolated dynamic index to DLQ

### LINKED ISSUE #718: DLQ when sprintf references a missing field
Proposal: When sprintf on the index name would fail because one or more fields do not exist, Logstash should DLQ the event instead of sending it to Elasticsearch.

---

Problem: 

Logstash's event sprintf has a behavior that when a field does not exist, the formatting string is left unaltered.

For example, if a user has this:

```
index => "%{[my][field]}-%{+YYYY}"
````

and supposing that `[my][field]` does not exist in the event, an index will be created in Elasticsearch literally as `%{[my][field]}-2017`. 

This is confusing and also tricky to recover from. It's tricky partly because of the `{}` and `[]` format and field-reference characters which `curl` uses (by default) with special meaning: globbing. So for a user to delete this index, they will experience an error:

```
% curl 'https://es.foo.com:9200/%{[my][field]]}-2017'
curl: (3) [globbing] nested brace in column 27
```

Or worse, if no nested fields are being used:

```
% curl -v 'http://localhost:9200/%{myfield}-2017.12.28'
> GET /%myfield-2017.12.28 HTTP/1.1
```

As above, curl interprets the `{}` to have special meaning, and this will certainly confuse users.

This is the beginning of a [yak shave](http://whatis.techtarget.com/definition/yak-shaving).

### PR DESCRIPTION
**Pull request by andsel**
## Release notes

Modified the resolution of dynamic index name so that in case of interpolation errors the event is sent to the DLQ. This feature could be explicitly disabled configuring properly the `dlq_on_failed_indexname_interpolation`.

## What does this PR do?
Update the the pre-indexing steps, so to that in case of an `IndexInterpolationError` is raised during the index name resolution, the event is sent to DLQ. It leverarges the refactored `#handle_dlq_status` from PR #1080 to reuse the enqueuing logic.

## Why is it important/What is the impact to the user?
Let the user to handle specifically the events which once indexed would create an ugly formatted name like  `%{[not_existing_field]}_index`.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- [x] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [x] run with 
```
.ci/docker-setup.sh && INTEGRATION=true .ci/docker-run.sh
```
- [x] adds feature flag to disable this behavior. Track telemetry data to know how many uses this explicit disabling.

## How to test this PR locally
- enable the DLQ,  set `dead_letter_queue.enable: true` in `config/logstash.yml`.
- launch an Elasticsearch instance
- execute a pipeline which wouldn't  resolve the index name like:
```
input {
	generator {
		message => '{"name": "John", "surname": "Doe"}'
		count => 1
		codec => json
	}
}

output {
	elasticsearch {
		index => "%{[not_existing_field]}"
		hosts => "http://localhost:9200"
		user => "elastic"
		password => "changeme"
	}
}
```
- then drain the DQL with another pipeline and verify it contains the previous failed event:
```
input {
  dead_letter_queue {
  	path => "/path_to/data/dead_letter_queue/"
  }
}

output {
  stdout {
    codec => rubydebug
  }

```
## Related issues

- Fixes #718
- Copies a refactoring done in #1080

## Use cases
As a user I don't want that unresolved index names generates unexpected indexes and I would to reprocess such failed events with another DLQ pipeline.

### CODE REVIEW

File: lib/logstash/outputs/elasticsearch.rb [hunk 1]
```diff
@@ -362,11 +365,43 @@ def config_init(params)
   # Receive an array of events and immediately attempt to index them (no buffering)
   def multi_receive(events)
     wait_for_successful_connection if @after_successful_connection_done
-    retrying_submit map_events(events)
+    events_mapped = safe_interpolation_map_events(events)
```
Comment (mashhurs) [inline lib/logstash/outputs/elasticsearch.rb:368]: How do you think if we reject index name unresolved events and only bring back successful events?
In my [unmerged PR](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1080/files#diff-221ddb62bde6d62966fab1051387ded7513fffd575cf0706a5f3a94ad2d31307R198), we had a great discussion with Ry and agreed to work with successful/submittable events here, send to DLQ rejected events wen filtering.

File: lib/logstash/outputs/elasticsearch.rb [hunk 2]
```diff
@@ -362,11 +365,43 @@ def config_init(params)
...
+    events.each do |event|
+       begin
+        successful_events << @event_mapper.call(event)
+       rescue IndexInterpolationError, e
+         action = event.sprintf(@action || 'index')
+         event_action_tuple = EventActionTuple.new(action, [], event)
+         failed_events << event_action_tuple
+       end
+    end
+    MapEventsResult.new(successful_events, failed_events)
```
Comment (mashhurs) [inline lib/logstash/outputs/elasticsearch.rb:399]:
```suggestion
    unless failed_events.empty?
      @logger.error("Can't map some events, needs to be handled by DLQ #{failed_events}")
      send_failed_resolutions_to_dlq(failed_events)
    end
    successful_events
```

File: lib/logstash/plugin_mixins/elasticsearch/common.rb [hunk 3]
```diff
@@ -206,19 +206,23 @@ def next_sleep_interval(current_interval)
...
-    def handle_dlq_status(message, action, status, response)
+    def handle_dlq_response(message, action, status, response)
+      _, action_params = action.event, [action[0], action[1], action[2]]
+      
+      # TODO: Change this to send a map with { :status => status, :action => action } in the future
+      detailed_message = "#{message} status: #{status}, action: #{action_params}, response: #{response}"
+      
+      log_level = dig_value(response, 'index', 'error', 'type') == 'invalid_index_name_exception' ? :error : :warn
+      
+      handle_dlq_status(action, log_level, detailed_message)
```
Comment (mashhurs) [inline lib/logstash/plugin_mixins/elasticsearch/common.rb:217]: Special thanks for including `handle_dlq_response` & `handle_dlq_status`!

**Review by mashhurs — CHANGES_REQUESTED** [review]

**Review by yaauie — APPROVED** [review]
Changes LGTM.

I'm not terribly fond of raising exceptions for flow control, but feel that the structure as-proposed here is simpler and _much_ more clear than alternatives.

My only concern is conflicts with the also-in-flight #1080, which similarly pre-filters events whose _action_ cannot be interpolated.

**Comment by mashhurs** [comment]
> Changes LGTM.
> 
> I'm not terribly fond of raising exceptions for flow control, but feel that the structure as-proposed here is simpler and _much_ more clear than alternatives.
> 
> My only concern is conflicts with the also-in-flight #1080, which similarly pre-filters events whose _action_ cannot be interpolated.

Initially I was thinking that seemed to me easily include my #1080 changes but it takes sometime to make an adjustment (especially unit test cases). Feel free to go first @andsel !
